name: test

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**

jobs:

  test:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run tests
        run:  go test -v ./...
